import { Noto_Sans } from "next/font/google";
import "@css/globals.css";
import Header from "@components/header/Header";
import Footer from "@components/footer/Footer";

const noto_san = Noto_Sans({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto_san.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
